name: Non-Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.1.0
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Non-Production Infrastructure: Global"
      service_account: plt-lz-identity-github@ptl-lz-terraform-tf05-nonprod.iam.gserviceaccount.com
      terraform_plan_args: -var-file=tfvars/non-production.tfvars
      terraform_state_bucket: plt-lz-identity-3bfe-nonprod
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: global-non-production
      working_directory: global/infra
      workload_identity_provider: projects/992372365053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
